# Generated by Django 5.0.7 on 2025-01-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', models.TextField()),
                ('sector_table_varname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartExternalCode',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInternalCode',
            fields=[
                ('part_id', models.IntegerField(primary_key=True, serialize=False)),
                ('internal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('storm_id', models.AutoField(primary_key=True, serialize=False)),
                ('mars_year', models.IntegerField()),
                ('sol', models.CharField(max_length=3)),
                ('mission_subphase', models.CharField(max_length=255)),
                ('solar_longitude_ls', models.DecimalField(decimal_places=6, max_digits=14)),
                ('centroid_longitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('centroid_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('area', models.DecimalField(decimal_places=6, max_digits=14)),
                ('member_id', models.CharField(max_length=255)),
                ('sequence_id', models.CharField(blank=True, max_length=20, null=True)),
                ('max_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('min_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('traits', models.CharField(max_length=255)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationSchedule',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DamagedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.IntegerField()),
                ('presumpted_or_reported', models.BooleanField()),
                ('cause_id', models.CharField(blank=True, max_length=7, null=True)),
                ('severity', models.IntegerField()),
                ('queued_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.conservationschedule')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.partsinternalcode')),
            ],
            options={
                'unique_together': {('part', 'internal_id')},
            },
        ),
        migrations.CreateModel(
            name='PartsUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.IntegerField()),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.installation')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.partsinternalcode')),
            ],
            options={
                'unique_together': {('installation', 'part')},
            },
        ),
    ]
