# Generated by Django 5.0.7 on 2025-01-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('installation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_latitude', models.IntegerField()),
                ('min_latitude', models.IntegerField()),
                ('max_longitude', models.IntegerField()),
                ('min_longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('storm_id', models.AutoField(primary_key=True, serialize=False)),
                ('mars_year', models.IntegerField()),
                ('sol', models.CharField(max_length=3)),
                ('mission_subphase', models.CharField(max_length=255)),
                ('solar_longitude_ls', models.DecimalField(decimal_places=6, max_digits=14)),
                ('centroid_longitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('centroid_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('area', models.DecimalField(decimal_places=6, max_digits=14)),
                ('member_id', models.CharField(max_length=255)),
                ('sequence_id', models.CharField(blank=True, max_length=20, null=True)),
                ('max_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('min_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.installation', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsage',
            fields=[
                ('part_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.installation', unique=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.part', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='sector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sector', unique=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('traits', models.CharField(max_length=255)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.speciality', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationSchedule',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.staff', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('damage_id', models.AutoField(primary_key=True, serialize=False)),
                ('presumpted_or_reported', models.BooleanField()),
                ('severity', models.IntegerField()),
                ('queued_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.conservationschedule', unique=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.part', unique=True)),
                ('cause_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.storm')),
            ],
        ),
    ]
