# Generated by Django 5.0.7 on 2025-01-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('installation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('max_latitude', models.IntegerField()),
                ('min_latitude', models.IntegerField()),
                ('max_longitude', models.IntegerField()),
                ('min_longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('storm_id', models.AutoField(primary_key=True, serialize=False)),
                ('mars_year', models.IntegerField()),
                ('sol', models.CharField(max_length=3)),
                ('member_id', models.IntegerField()),
                ('centroid_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('centroid_longitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('duration', models.DecimalField(decimal_places=6, max_digits=14)),
                ('mission_subphase', models.CharField(max_length=255)),
                ('spread_latitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('spread_longitude', models.DecimalField(decimal_places=6, max_digits=14)),
                ('power', models.IntegerField()),
                ('stone_damage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.installation')),
            ],
        ),
        migrations.CreateModel(
            name='PartsUsage',
            fields=[
                ('part_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.installation')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.part')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.sector'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('traits', models.CharField(max_length=255)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationSchedule',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('damage_id', models.AutoField(primary_key=True, serialize=False)),
                ('presumpted_or_reported', models.BooleanField()),
                ('severity', models.IntegerField()),
                ('queued_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.conservationschedule')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.part')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.storm')),
            ],
        ),
    ]
