# Generated by Django 5.0.7 on 2025-01-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationschedule',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.staff'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='cause_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.storm'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.part'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='queued_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.conservationschedule'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='sector_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.sector'),
        ),
        migrations.AlterField(
            model_name='part',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.installation'),
        ),
        migrations.AlterField(
            model_name='partsusage',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.installation'),
        ),
        migrations.AlterField(
            model_name='partsusage',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.part'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.speciality'),
        ),
    ]
