# Generated by Django 4.2.16 on 2025-01-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_sector_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Damage', to='db.part'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Installation', to='db.sector'),
        ),
        migrations.AlterField(
            model_name='part',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Part', to='db.installation'),
        ),
        migrations.AlterField(
            model_name='partsusage',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PartsUsage', to='db.installation'),
        ),
        migrations.AlterField(
            model_name='partsusage',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PartsUsage', to='db.part'),
        ),
    ]
